<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Mobiles</name>
   <tag></tag>
   <elementGuidId>73c41411-6f43-4cce-bf64-2403e1b281b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-wrapper']/div/div[3]/div[4]/ul/li/a/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.info-title--3CkVD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mobiles 51,485 ads&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>39c14410-22f3-4963-bf4e-fcec277bfe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>info-title--3CkVD</value>
      <webElementGuid>103c5245-e407-42c2-b344-3d10bca24669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobiles</value>
      <webElementGuid>5a27e468-6b3d-4de5-8af9-1c2b007fcc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-wrapper&quot;)/div[@class=&quot;top-container--12FJu all justify-content-flex-start--1Xozy align-items-normal--vaTgD flex-wrap-nowrap--3IpfJ flex-direction-column--3aExp flex--3fKk1&quot;]/div[@class=&quot;desktop-max-width-container--3xntY main-content-area--o-zsx skeleton-content--2JN5q&quot;]/div[@class=&quot;section--3qPXi category-container--1RreD&quot;]/ul[@class=&quot;category-list--2oS_W right--WcHqY left--2ndlm hide-native-scrollbar--Nj_rv&quot;]/li[@class=&quot;category-item--1h1A1&quot;]/a[@class=&quot;link--1t8hM gtm-home-category-link-click&quot;]/div[@class=&quot;info--uF0qH&quot;]/p[@class=&quot;info-title--3CkVD&quot;]</value>
      <webElementGuid>6bbcfe48-ec8c-43bb-8bde-ccf9121fc846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-wrapper']/div/div[3]/div[4]/ul/li/a/div[2]/p</value>
      <webElementGuid>c27790e1-584b-43bc-8e62-81b5bb9067be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse items by category'])[1]/following::p[1]</value>
      <webElementGuid>5cc301f8-e4fe-46e3-8b02-59e41d7bf941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All of Bangladesh'])[1]/following::p[1]</value>
      <webElementGuid>ac3e3d33-7828-4c4b-9d93-df6613247130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start making money!'])[1]/preceding::p[16]</value>
      <webElementGuid>b0e43f5b-19c5-4398-a4c1-a3a062020320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post your ad for free'])[1]/preceding::p[17]</value>
      <webElementGuid>c40815d7-d92d-4ecd-839d-6deff7c2b2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobiles']/parent::*</value>
      <webElementGuid>1114e27b-106e-4602-a39c-99b6e3f86de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>6c4d9577-181b-45cc-a34a-5d6bff5a6ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Mobiles' or . = 'Mobiles')]</value>
      <webElementGuid>7301f5bc-ba17-4fd9-886a-e47286232157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
