<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>13f0a835-28a3-478a-8de9-d250922f4f8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-wrapper']/div/div[2]/div/nav/div/ul[2]/li[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.header-link--woAbP.title--1NHWk.gtm-login-click.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Login&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00aa5435-3463-4765-b152-af834228bbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>726287e5-160b-42b2-9480-6772a96f34df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-link--woAbP title--1NHWk gtm-login-click active</value>
      <webElementGuid>42274e54-0324-4c69-a33b-b43adff824e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>276929e5-ab24-4669-b6da-24ab189b85c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>d317667b-e992-4022-b234-350dd846ea88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/?login-modal=true&amp;redirect-url=/</value>
      <webElementGuid>d037b23a-a4b8-427d-92f7-9b500d3d0e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>012153d1-7240-4425-b883-71e38c751cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-wrapper&quot;)/div[@class=&quot;top-container--12FJu all justify-content-flex-start--1Xozy align-items-normal--vaTgD flex-wrap-nowrap--3IpfJ flex-direction-column--3aExp flex--3fKk1&quot;]/div[@class=&quot;only-desktop--2pxYG&quot;]/div[1]/nav[@class=&quot;nav--1qSMY background--2lR9B&quot;]/div[@class=&quot;justify-content-space-between--bjSys align-items-center--159cZ flex-wrap-nowrap--3IpfJ flex-direction-row--27fh1 flex--3fKk1&quot;]/ul[@class=&quot;nav-bar-list--201Xv&quot;]/li[@class=&quot;login-icon-container--3oQMU&quot;]/div[@class=&quot;justify-content-flex-start--1Xozy align-items-center--159cZ flex-wrap-nowrap--3IpfJ flex-direction-row--27fh1 flex--3fKk1&quot;]/a[@class=&quot;header-link--woAbP title--1NHWk gtm-login-click active&quot;]</value>
      <webElementGuid>03ed0bb6-14db-4218-8900-645905a8e6db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-wrapper']/div/div[2]/div/nav/div/ul[2]/li[2]/div/a</value>
      <webElementGuid>6cd3292c-c3c9-4b14-9e27-fc19f715e918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat'])[1]/following::a[1]</value>
      <webElementGuid>b6b60e77-d387-4009-9bc0-5c8f0e80a6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='বাংলা'])[1]/following::a[2]</value>
      <webElementGuid>54c0dc80-bad5-4018-b3d2-1998bcaab830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POST YOUR AD'])[1]/preceding::a[1]</value>
      <webElementGuid>7b3d8462-ec55-42ef-93c3-383dee266ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/?login-modal=true&amp;redirect-url=/')])[2]</value>
      <webElementGuid>c948905d-9c19-49c0-8d6a-d28b81d261ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a</value>
      <webElementGuid>6fb3eef8-5013-42f4-b783-62cdac4eeef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/?login-modal=true&amp;redirect-url=/' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>084e292b-7957-45af-847e-dbf39dd37fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
