<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_All of Bangladesh_query</name>
   <tag></tag>
   <elementGuidId>2b0ec6df-3269-4aab-a663-c7ca0b9eba6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='query']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;query&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;What are you looking for?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e191b36c-3627-4263-b875-460a72e08437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>08829fed-683e-45e8-a1ad-f146af3b498f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>295e22c1-9c15-429e-8dc7-f54387ee8a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8aaa3030-5076-40d2-b6cd-b5ba4267b297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search input</value>
      <webElementGuid>f0f4abe5-1c6f-47d3-89b3-20fed77938c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-input--PtfH8</value>
      <webElementGuid>605e2d76-8f83-4a6f-b324-00c713a4f103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What are you looking for?</value>
      <webElementGuid>f20c4962-ce93-4dc8-99f0-dc6a07688894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-wrapper&quot;)/div[@class=&quot;top-container--12FJu all justify-content-flex-start--1Xozy align-items-normal--vaTgD flex-wrap-nowrap--3IpfJ flex-direction-column--3aExp flex--3fKk1&quot;]/div[@class=&quot;desktop-max-width-container--3xntY main-content-area--o-zsx skeleton-content--2JN5q&quot;]/div[@class=&quot;search-container--1aaDi justify-content-center--3YVEn align-items-flex-end--Fg8OY flex-wrap-nowrap--3IpfJ flex-direction-row--27fh1 flex--3fKk1&quot;]/div[@class=&quot;section--3qPXi inner--2X7Be justify-content-flex-end--jceWj align-items-center--159cZ flex-wrap-nowrap--3IpfJ flex-direction-column--3aExp flex--3fKk1&quot;]/div[@class=&quot;search-bar-container--tnPU2&quot;]/form[@class=&quot;search-form--mexm-&quot;]/input[@class=&quot;search-input--PtfH8&quot;]</value>
      <webElementGuid>c09d8295-c37b-4373-bcba-ccde78d57b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='query']</value>
      <webElementGuid>f45cca83-aa9a-4cef-a797-19e33887518d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-wrapper']/div/div[3]/div[2]/div/div/form/input</value>
      <webElementGuid>40f061f4-0b5a-4647-b21c-cda4ccb09b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c608c984-5654-4d8f-9b67-54715273fbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'query' and @type = 'search' and @placeholder = 'What are you looking for?']</value>
      <webElementGuid>75d62435-e85b-47c0-b3b1-1ac60a18724c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
